site_name: Tool Forge Documentations
site_url: https://github.com/benjoe93/tool-docs
theme:
  name: material
  features:
    - navigation.footer: false
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/book-open
  # favicon: material/book-open
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: green
      accent: light green

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: green
      accent: light green

markdown_extensions:
  - attr_list
  - md_in_html
  
  # Text formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.blocks.caption
  
  # Emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  # Code formatting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # callouts
  - admonition
  - pymdownx.details
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/benjoe93
    - icon: fontawesome/brands/artstation
      link: https://www.artstation.com/benjoe
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/benblazer/